### PR TITLE
[16.0][FIX] automation_oca: pass eval_context in domain

### PR DESCRIPTION
**Pull request by gaelTorrecillas**
Hello,
 Following my first pr #8 , when we use a domain with today, datetime etc, we have an error when we add step.
So I add context in safe_eval contained in the step file.

### CODE REVIEW

**Review by flotho — CHANGES_REQUESTED** [review]
IMHO, the message should be `pass eval_context in domain`

**Review by flotho — APPROVED** [review]
LGTM

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Comment by flotho** [comment]
thanks @pedrobaeza , we really appreciate your approbation.
Regards

**Comment by gaelTorrecillas** [comment]
thanks you for yours review and approbation.

**Pull request merged**
